### ISSUE TITLE
Reference document on standard annotations used in OBO ontologies

### ISSUE THREAD

**Issue by shawntanzk** [OBOAcademy/obook#130]
Have made a start here:
https://docs.google.com/spreadsheets/d/149Go0rGKiDbtZSMgazV1R9Ld9ViUinkO7cynTND7sDg/edit#gid=0
Happy for comments/feedback (esp in terms of structure)

**Comment by matentzn** [comment]
You are treading a fine line here between descriptive (which is good) and pre-scriptive (which does not belong in obook - it belongs in https://github.com/information-artifact-ontology/ontology-metadata/issues).

Its good to work on this though - IMO the _actual_ properties to be used, i.e. the actual recommendation, should be carefully embedded as "Best practice" in the "GO-style curator pathway" - because it is not nearly universally agreed what properties to use. 

This is probably another good source of inspiration:
https://github.com/obophenotype/uberon/blob/master/src/sparql/illegal-annotation-property-violation.sparql

But @zhengj2007 has a much more detailed list which she curates. 

But feel free to continue curating a minimal list you think reflects CL/Uberon/GO/PATO practice - this will be super useful also for the OMO workshop in April.

**Comment by shawntanzk** [comment]
> You are treading a fine line here between descriptive (which is good) and pre-scriptive (which does not belong in obook

Think we talked a little about this last meeting @dosumis.

> "Best practice" in the "GO-style curator pathway"

The intention was for that pathway, and in my mindset, really prescriptive for that set, but totally understand why it can't be in obook as is. Wondering if we could have it as a "hidden" document that only appears as a reference in the GO-style curator pathway?

**Comment by matentzn** [comment]
No need to hide it if it is clearly labelled as such. It reflects, after all, best practice for a large sub-community of OBO. Documenting that is part of the OBOOK agenda. Just name the file:

go-style-annotation-property-practice.md

And add a headline:

```
# Recommended metadata properties to use in curating OBO ontologies (GO-style)

Note that while most of the practices documented here apply to all OBO ontologies this recommendation applies only to ontologies that are developed using [GO-style](link-to-go-style-pathways.md) curation workflows.

..... Properties...
```

**Comment by matentzn** [comment]
The reason why I say, "does not belong in obook" is not because it is best practice, but because there are some debates here that will likely change these recommendations soon, and these debates should not be had here in OBOOK, but as part of OMO.

**Comment by dosumis** [comment]
Most of this is just documenting the standards that come from OBO format.  Almost every ontology with roots in OBO format follows the basic pattern of AP axioms - with some small divergences. So, much broader than GO/CL/Uberon/PATO.  Agree this needs to evolve, but ideally in co-ordinated fashion.

**Comment by matentzn** [comment]
Yes.. This is what I hoped my main reason for being engaged in OBO was going to be :P Coordinating the harmonisation of these APs. But it is some difficult process.

**Comment by shawntanzk** [comment]
Fixed here https://github.com/OBOAcademy/obook/pull/131
Closing this ticket, but if there needs to be additions or change, please open a new ticket
