### ISSUE TITLE
Effective ChatGPT Prompting for Ontology Curators

### ISSUE THREAD

**Issue by matentzn** [OBOAcademy/obook#401]
see #400 

I am completely in unchartered territory for this one, so could do with some help on how to evolve this.

I am thinking:

- Basic prompting for research on definitions and synonyms
- create SSSOM mappings to other ontologies
- advanced applications like ontogpt and kg curation

Please also tell me if you think the whole idea makes no sense.

**Comment by caufieldjh** [comment]
Some coverage of NLP basics in the context of interacting with LLMs (like "what is a token anyway") may be helpful.

I'm also thinking about how this tutorial could be future-proofed, since we're in a weird time when OpenAI models are the best at what what they do but may not be for long. There are also use cases that may require running models locally. An introduction to Huggingface and Huggingface Spaces could address both of those issues without getting too bogged down in ever-changing technical details.
Like so: https://huggingface.co/docs/transformers/model_doc/opt
and like so: https://huggingface.co/spaces/Pippoz/Hugging_Space

**Comment by matentzn** [comment]
Thanks a ton @caufieldjh will look into this line of thinking!

**Comment by matentzn** [comment]
We did a first round of this now, will open a new one when need arises
