### ISSUE TITLE
add additional resources to Ontology user pathway doc

### ISSUE THREAD

**Issue by sbello** [OBOAcademy/obook#432]
@nicolevasilevsky Another resource to add to the new page for using ontologies
From the Mastodon ask:
https://link.springer.com/book/10.1007/978-1-4939-3743-1 ([Marc Robinson-Rechavi](https://mstdn.social/@marcrr@ecoevo.social))

Note, I still get a giant dangerous page don't go here warning when I try to go to the obook site (see #419)

**Comment by sbello** [comment]
Another possible addition
https://tess.elixir-europe.org/search?q=ontology
from [Egon Willighagen ](https://mstdn.social/@egonw@scholar.social)

**Comment by nlharris** [comment]
@sierra-moxon is writing an article entitled "Using Ontologies in Practice - LinkML can help!" that is intended as a gentle introduction for users. When it's ready, we'd like to have a link to it added to the user pathways page (https://oboacademy.github.io/obook/pathways/ontology-user/).
(BTW, I strongly encourage others to include explicit URLs in their issues like that, so that we're not trying to guess what "the new page for using ontologies" is. 😉)

**Comment by nicolevasilevsky** [comment]
@sbello I added the Gene Ontology handbook

The other link to the elixr resources looks l like a collection of resources. I think it would be best to review these and organize them, rather than just linking to the collection of search results, but I don't have bandwidth to do that. Please feel free to do so, if you are inclined.

@nlharris do you want to keep this ticket open until Sierra's content is added? Or you can create a separate ticket for that action item and we can close this one.

**Comment by nlharris** [comment]
yeah, go ahead and close this one

**Comment by nicolevasilevsky** [comment]
will do! @sbello please feel free to reopen if you'd like to take further action.
